Proxy:
  HttpServer:
    addr: ":8080"
  GrpcServer:
    Addr: ":8081"
Discovery:
  Service: "etcd"
  ETCD:
    UserName: "user"
    Password: "password"
    WatchPrix: "service/"
    EndPoints:
      - "localhost:1111"
      - "localhost:2222"
      - "localhost:3333"
    DailTimeout: 5   #
Hystrix:
  Degrade:
    Timeout: 100000
    MaxConcurrentRequests: 100
    RequestVolumeThreshold: 10
    ErrorPercentThreshold: 25
  Fuse:
    Timeout: 100000
    MaxConcurrentRequests: 100
    RequestVolumeThreshold: 10
    ErrorPercentThreshold: 25




