HttpServer:
  Addr: ":8080"
GrpcServer:
  Addr: ":8081"
Hystrix:
  Degrade:
    Timeout: 100000
    MaxConcurrentRequests: 100
    RequestVolumeThreshold: 10
    ErrorPercentThreshold: 25
  Fuse:
    Timeout: 100000
    MaxConcurrentRequests: 100
    RequestVolumeThreshold: 10
    ErrorPercentThreshold: 25
JWT:
  Enable: false
ETCD:
  Enable: false
  WatchPrix: "service/"
  EndPoints:
    - "localhost:1111"
    - "localhost:2222"
    - "localhost:3333"
  DailTimeout: 5   #
LoadBalance:
  Algorithm: 2   # WeightedRoundRobin = 1 / RoundRobin = 2 / consistentHashing = 3  | default = 2




